export enum ScenesNames {
  ChooseOrderCount = 'chooseOrderCount',
  MultipleOrdersNote = 'multipleOrdersNote',
  ChooseOrderDescriptionType = 'chooseOrderDescriptionType',
  AddOrderPhotoDescription = 'addOrderPhotoDescription',
  AddOrderTextDescription = 'addOrderTextDescription',
  ChooseDeliveryType = 'chooseDeliveryType',
  AddDeliveryAddress = 'addDeliveryAddress',
  AddCarInfoScene = 'addCarInfoScene',
  AddCarDocsPhoto = 'addCarDocsPhoto',
  AddCarVinNumber = 'addCarVinNumber',
  AddCarDescription = 'addCarDescription',
  ChooseOrderQuality = 'chooseOrderQuality',
  ChooseOrderUrgency = 'chooseOrderUrgency',
  CreateOrder = 'createOrder',
}
