export const buttonsValue = Object.freeze({
  singleOrderBtn: 'Хочу заказать запчасти для одного автомобиля.',
  multipleOrdersBtn: 'Мне нужны запчасти для нескольких автомобилей.',
  multipleOrdersOKBtn: 'Понятно!',
  addPhotoDescriptionBtn: 'Добавить фото',
  addTextDescriptionBtn: 'Добавить описание',
  orderFromPointBtn: 'Заберу готовый заказ в точке выдачи',
  orderWithDeliveryBtn: 'Нужна доставка',
  addCarDocsPhotoBtn: 'Добавить фото ПТС',
  addCarVinNumberBtn: 'Добавить VIN номер',
  addCarDescriptionBtn: 'Добавить дополнительные параметры',
  orderOriginalQualityBtn: 'Только оригинал',
  orderCheapQualityBtn: 'Чем дешевле, тем лучше',
  orderBaseQualityBtn: 'Лучшее соотношение цены и качества',
  lowUrgensyOrderBtn: 'Запчасти из наличия',
  highUrgencyOrderBtn: 'Готов подождать',
});
