export const buttonsValue = Object.freeze({
  singleOrderBtn: 'Хочу заказать запчасти для одного автомобиля.',
  multipleOrdersBtn: 'Мне нужны запчасти для нескольких автомобилей.',
  multipleOrdersOKBtn: 'Понятно!',
  addPhotoDescriptionBtn: 'Добавить фото',
  addTextDescriptionBtn: 'Добавить описание',
  orderFromPointBtn: 'Заберу готовый заказ в точке выдачи',
  orderWithDeliveryBtn: 'Нужна доставка',
  addCarDocsPhotoBtn: 'Добавить фото ПТС',
  addCarVinNumberBtn: 'Добавить VIN номер',
  addCarDescriptionBtn: 'Добавить дополнительную информацию',
  orderOriginalQualityBtn: 'Только оригинал',
  orderCheapQualityBtn: 'Чем дешевле, тем лучше',
  orderBaseQualityBtn: 'Лучшее соотношение цены и качества',
  lowUrgensyOrderBtn: 'Запчасти из наличия',
  highUrgencyOrderBtn: 'Готов подождать',
  confirmOrderBtn: 'Я подтверждаю заказ',
  changeOrderDescriptionBtn: 'Изменить описание запчасти',
  changeOrderPhotoBtn: 'Изменить фото необходимого',
  changeDeliveryTypeBtn: 'Изменить тип доставки',
  changeDeliveryAddressBtn: 'Изменить адресс доставки',
  changeCarDocsPhotoBtn: 'Изменить фото ПТС',
  changeCarVinNumberBtn: 'Изменить VIN номер',
  changeCarDescriptionBtn: 'Изменить доп информацию',
  changeOrderQuality: 'Изменить качество',
  changeOrderUrgency: 'Изменить сроки',
  startNextOrder: 'Да, сделаем еще один заказ',
  stopCreateOrders: 'Нет, на этом все',
  sendClientMessage: 'Отправить сообщение',
  changeClientMessage: 'Изменить сообщение',
  stopSendClientMessage: 'Отменить',
});
